"""rename department

Revision ID: 6e07218a6d7e
Revises: 7e52ffc2e3f5
Create Date: 2024-06-29 20:16:34.078857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e07218a6d7e'
down_revision = '7e52ffc2e3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###